SIM ?= icarus
TOPLEVEL_LANG ?= verilog
SRC_DIR = $(PWD)/../src

SIM_BUILD = sim_build/spi
VERILOG_SOURCES = $(SRC_DIR)/mem/spi_flash_read.v $(PWD)/spi_flash_read_tb.v
COMPILE_ARGS += -I$(SRC_DIR)
TOPLEVEL = spi_flash_read_tb
COCOTB_TEST_MODULES = test_spi_flash_read
COCOTB_RESULTS_FILE = results-spi.xml

include $(shell cocotb-config --makefiles)/Makefile.sim
