SIM ?= icarus
TOPLEVEL_LANG ?= verilog
SRC_DIR = $(PWD)/../src

SIM_BUILD = sim_build/mem
VERILOG_SOURCES = $(SRC_DIR)/mem/spi_mem_ctrl.v $(SRC_DIR)/mem/spi_mem_bridge.v $(PWD)/spi_mem_bridge_tb.v
COMPILE_ARGS += -I$(SRC_DIR)
TOPLEVEL = spi_mem_bridge_tb
COCOTB_TEST_MODULES = test_spi_mem_bridge
COCOTB_RESULTS_FILE = results-mem.xml

include $(shell cocotb-config --makefiles)/Makefile.sim
